# docker service rm lanl0rd_w0rks_js_angular || true && docker stack deploy -c $(pwd))/stack.yaml --resolve-image=never lanl0rd_w0rks_js

version: '3.7'

services:

  angular:
    image: lanl0rd/js
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "4200:4200"
    volumes:
      - $(pwd):/app
    working_dir: /app
    command: sh -c "npm i && ng serve"