# docker service rm w0rks_js-works || true && docker stack deploy -c $(pwd)/works.yaml --resolve-image=never w0rks

version: '3.7'

services:

  js-works:
    image: lanl0rd/w0rks:amd
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    command: tail -f /dev/null