# docker service rm lanl0rd_w0rks_js_nest || true && docker stack deploy -c $(pwd)/stack.yaml --resolve-image=never lanl0rd_w0rks_js

version: '3.7'

services:

  nest:
    image: lanl0rd/js
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "3000:3000"
    volumes:
      - $(pwd):/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /app
    command: sh -c "npm i && npm run start:dev"